gitSourceBranch = "master"

[home]
enabled = false
includeReadme = false

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

[docusaurus.themeConfig.colorMode]
respectPrefersColorScheme = true
defaultMode = "dark"
